server:
    servlet:
      context-path: /
      session: 
        timeout: 1080000
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: UTF-8
    port: 9008
    compression:
      enabled: true
      
spring:
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  activemq:
    broker-url: tcp://54.222.16
    in-memory: true
    pool:
      enabled: true
    user:  admin
    password: CyRd1598


  mail:
    host: smtp.partner.outlook.cn
    username: o
    password: On
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          socketFactory:
            fallback: true

    default-encoding: utf-8
    protocol: smtp
    port: 587
    
    
  datasource:
    email:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://one2c-rdb.cjlz0b2d0bwx.rds.cn-north-1rue&characterEncoding=utf8
      username: emai
      password: IVuuVYqflqZv7VI5OFXkg13uMV5n+x7/YFl37+N+/T91QMS4tdHQ==
      initialSize: 1
      minIdle: 3
      maxActive: 150
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #validationQuery: select 'x'
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 80
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,wall,log4j,slf4j
      #filters: config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI2/OzsP/puUprsEpCxm/PA0tg7DJIZvayRm48Fv7saFcDSS1CGTj6QLb1bIDiGSSk5mdvSVsle0k7Z3JdoYazkCAwEAAQ==
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      removeAbandoned: true
      removeAbandonedTimeout: 18000
    sdn:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://one2c-rdb.cjlz0b2d0c_pro?useUnicode=true&characterEncoding=utf8
      username: cy
      password: AJIrpQCXEpVeywCXvjPf6XbQvBobpWHKPkxR/Rpg==
      initialSize: 1
      minIdle: 3
      maxActive: 150
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #validationQuery: select 'x'
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 80
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,wall,log4j,slf4j
      #filters: config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALH7SC9Cb74zF81Mp3GMdg1vSx9TRNfA91Hb7zNl7C5g9N9DRAh2etLJUi7Q+RAakepNXltN0aFfAfJN0QQtn+UCAwEAAQ==
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      removeAbandoned: true
      removeAbandonedTimeout: 18000

email-system-config: 
    email-channel: MSG_CHANNEL_EMAIL_SERVER_PRO

logging:
  config: classpath:logback-spring.xml
