server:
    servlet:
      context-path: /
      session: 
        timeout: 1080000
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: UTF-8
    port: 8889
    compression:
      enabled: true
      
spring:
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  activemq:
    broker-url: tcp://192.168.10.81:61616
    in-memory: true
    pool:
      enabled: true
    user:  lucas
    password: lucas123


  mail:
    host: smtp.partner.outlook.cn
    username: one2c@cypresstel.com
    password: One@C1306
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          socketFactory:
            fallback: true

    default-encoding: utf-8
    protocol: smtp
    port: 587
    
    
  datasource:
    email:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.81:3306/emailqat?useUnicode=true&characterEncoding=utf8
      username: cuicui_dev
      password: DVAs7Q9NtcTVGJvdKlXwhqTYp0qoDL4POxQ03uzGZSqd4PFBR9HW16aHrYjN8n+x9rH6gkhPZZAAADwmQIeDnQ==
      initialSize: 1
      minIdle: 3
      maxActive: 150
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #validationQuery: select 'x'
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 80
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,wall,log4j,slf4j
      #filters: config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKJjPXOpVrmoxWBSDXK1QZx1YNqnIhwcWhY9YOLLfR7Z0UGQJVlm6ljmZUVproM2tJDR91pIXt8cQShvpnrPvKECAwEAAQ==
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      removeAbandoned: true
      removeAbandonedTimeout: 18000
    sdn:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.81:3306/SD_DCI_test?useUnicode=true&characterEncoding=utf8
      username: sd_dci_test
      password: 1as6tqKBXe3XHn6ccd4F/+RUm4VU+UBwH9X+ERqAyFeYv4ntEfGM0qKOeB7i1odVr5aqAHuV2cHi9xF8ftqqKQ==
      initialSize: 1
      minIdle: 3
      maxActive: 150
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #validationQuery: select 'x'
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 80
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,wall,log4j,slf4j
      #filters: config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPB/sSkZyUj8Hb8TDjEnt70CEjjCK0jww0v8QC67FoQFiQYYSLBmMQekVxqA6xd/0OdJTYmed6ae4R7NTK9dBb0CAwEAAQ==
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      removeAbandoned: true
      removeAbandonedTimeout: 18000

email-system-config: 
    email-channel: MSG_CHANNEL_EMAIL_SERVER_QAT

logging:
  config: classpath:logback-spring.xml
