server:
    servlet:
      context-path: /
      session: 
        timeout: 1080000
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: UTF-8
    port: 80
    compression:
      enabled: true
      
sdn: 
   name: lucas-lulu
      

